image: mcr.microsoft.com/java/maven:8u202-zulu-debian9

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/"

cache:
  paths:
    - .m2/

stages:
  - compile
  - test
  - build

compile:
  stage: compile
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

build:
  stage: build
  script:
    - mvn package
  artifacts:
    expire_in: 1 day
    paths:
      - xdef/target/*.jar
      - xscript-api/target/*.jar
